spring.application.name=home-inspection

spring.datasource.url=jdbc:sqlite:D:\\Projects\\Home-inspection-project\\database.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=1000MB